// <auto-generated />
using System;
using ComuniDev.WebEFCore.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RegaloOriginal.Migrations
{
    [DbContext(typeof(RegaloOriginalDbContext))]
    [Migration("20230214183614_Initial Create")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComuniDev.WebEFCore.API.Models.ItemVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ItemVenta");
                });

            modelBuilder.Entity("ComuniDev.WebEFCore.API.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItemVentaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ItemVentaId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ComuniDev.WebEFCore.API.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ItemVentaId")
                        .HasColumnType("int");

                    b.Property<int>("MontoTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemVentaId");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("ComuniDev.WebEFCore.API.Models.Producto", b =>
                {
                    b.HasOne("ComuniDev.WebEFCore.API.Models.ItemVenta", null)
                        .WithMany("ProductoId")
                        .HasForeignKey("ItemVentaId");
                });

            modelBuilder.Entity("ComuniDev.WebEFCore.API.Models.Venta", b =>
                {
                    b.HasOne("ComuniDev.WebEFCore.API.Models.ItemVenta", null)
                        .WithMany("VentaId")
                        .HasForeignKey("ItemVentaId");
                });

            modelBuilder.Entity("ComuniDev.WebEFCore.API.Models.ItemVenta", b =>
                {
                    b.Navigation("ProductoId");

                    b.Navigation("VentaId");
                });
#pragma warning restore 612, 618
        }
    }
}
